name: Cachix
on:
  pull_request:
  push:
jobs:
  build-to-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v15
      with:
        name: qbot
        authToken: '${{ secrets.CACHIX_AUTHTOKEN }}'
    - run: nix build
    - run: ./result/bin/qbot --help
    - run: echo OK
